const express=require('express')
const { allproduct, singleproduct } = require('../controllers/userproducts')
const { userorders } = require('../controllers/userorders')
const { registerformController } = require('../controllers/registerform')
const { userloginController } = require('../controllers/userloginController')
const { registerformControllerUpdate } = require('../controllers/registerformUpdate')
const router=express.Router()
router.get('/product',allproduct)
router.get('/product/:id',singleproduct)
router.post('/order',userorders)
router.post('/registerform',registerformController)
router.put('/registerform/:id',registerformControllerUpdate)
router.get('/userlogin',userloginController)
module.exports=router
