const express=require("express")
const { allproduct, singleproduct } = require('../controllers/userproducts')
const { userorders } = require('../controllers/userorders')
const { registerformController } = require('../controllers/registerform')
const { userloginController } = require('../controllers/userloginController')
const { registerformControllerUpdate } = require('../controllers/registerformUpdate')
const { registerMobileController } = require('../controllers/registerMobileController')
const { getMobileRegisterData } = require("../controllers/getMobileRegisterData")
const { registerMobileFormController } = require("../controllers/postRegisterMobileFormController")
const { updateMobileRegisterForm } = require("../controllers/updateMobileRegisterForm")
const router=express.Router()

router.post('/mobileform',registerMobileFormController)
router.get('/product',allproduct)
router.get('/product/:id',singleproduct)
router.post('/order',userorders)
router.post('/registerform',registerformController)
router.put('/registerform/:id',registerformControllerUpdate)
router.get('/userlogin',userloginController)
router.post('/registermobile',registerMobileController)
router.get('/getMobileRegisterData',getMobileRegisterData)
router.put('/mobileform/:mobile',updateMobileRegisterForm)

module.exports=router
