const express=require("express")
const { allproduct, singleproduct } = require('../controllers/userproducts')
const { userorders } = require('../controllers/userorders')
const { registerformController } = require('../controllers/registerform')
const { userloginController } = require('../controllers/userloginController')
const { registerformControllerUpdate } = require('../controllers/registerformUpdate')
const { registerMobileController } = require('../controllers/registerMobileController')
const { getMobileRegisterData } = require("../controllers/getMobileRegisterData")
const { registerMobileFormController } = require("../controllers/postRegisterMobileFormController")
const { updateMobileRegisterForm } = require("../controllers/updateMobileRegisterForm")
const { hoodieproducts, hoodieproduct } = require("../controllers/hoodieproducts")
const { tshirtproducts, tshirtproduct } = require("../controllers/tshirtproducts")
const { tpantproducts, tpantproduct } = require("../controllers/tpantproducts")
const { chudiproducts, chudiproduct } = require("../controllers/chudiproducts")
const { legginsproducts, legginsproduct } = require("../controllers/legginsproducts")
const { shortsproducts, shortsproduct } = require("../controllers/shortsproducts")
const { sareeproducts, sareeproduct } = require("../controllers/sareeproducts")
const { nightwearproducts, nightyproduct } = require("../controllers/nightwearproducts")
const router=express.Router()

router.post('/mobileform',registerMobileFormController)
router.get('/product',allproduct)
router.get('/hoodie',hoodieproducts)
router.get('/tshirt',tshirtproducts)
router.get('/tpant',tpantproducts)
router.get('/chudi',chudiproducts)
router.get('/leggins',legginsproducts)
router.get('/shorts',shortsproducts)
router.get('/saree',sareeproducts)
router.get('/nightwear',nightwearproducts)
router.get('/product/:id',singleproduct)
router.get('/hoodie/:id',hoodieproduct)
router.get('/tshirt/:id',tshirtproduct)
router.get('/tpant/:id',tpantproduct)
router.get('/chudi/:id',chudiproduct)
router.get('/leggins/:id',legginsproduct)
router.get('/shorts/:id',shortsproduct)
router.get('/saree/:id',sareeproduct)
router.get('/nightwear/:id',nightyproduct)
router.post('/order',userorders)
router.post('/registerform',registerformController)
router.put('/registerform/:id',registerformControllerUpdate)
router.get('/userlogin',userloginController)
router.post('/registermobile',registerMobileController)
router.get('/getMobileRegisterData',getMobileRegisterData)
router.put('/mobileform/:mobile',updateMobileRegisterForm)
module.exports=router
